// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzjS4t3deTs_rAqKXaFkxa1II8wHeqKs4',
    appId: '1:354482627195:web:2d6b7fd93e9afe043bb8de',
    messagingSenderId: '354482627195',
    projectId: 'mondkapjesmelder',
    authDomain: 'mondkapjesmelder.firebaseapp.com',
    storageBucket: 'mondkapjesmelder.appspot.com',
    measurementId: 'G-6QL9MQC715',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_yTcQUX1uPatdEGRJFm5uOqKl96fI9MU',
    appId: '1:354482627195:android:7a40192133c06f833bb8de',
    messagingSenderId: '354482627195',
    projectId: 'mondkapjesmelder',
    storageBucket: 'mondkapjesmelder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6eAo5hLs1RUlhokA72KZR7X7V63VYbI',
    appId: '1:354482627195:ios:60ee8379681a7f573bb8de',
    messagingSenderId: '354482627195',
    projectId: 'mondkapjesmelder',
    storageBucket: 'mondkapjesmelder.appspot.com',
    iosClientId: '354482627195-b32u729nqgl1l1b82to11dgi65f1vhhq.apps.googleusercontent.com',
    iosBundleId: 'com.hotboys.mondkapjesmelder',
  );
}
